// eslint-disable-next-line import/prefer-default-export
export const fundData = {
  nameEn: 'Fund 11',
  nameAr: 'Fund (AR) 11',
  assetsClass: 'equity',
  fundManagerId: '1',
  fundManagerName: 'John Doe',
  type: 'open',
  city: 'London',
  coverage: 1000_000,
  minCoverage: 1000,
  minInvestment: 10_000,
  investmentStartingDate: '2023-01-01',
  investmentEndingDate: '2023-12-31',
  expectedRoi: 20,
  duration: '3',
  status: 'pendingApproval',
  subscriptionFeesPercentage: 2,
  unitPrice: 1000,
  units: 10,
  distributionFees: 12,
  riskMessageEn: 'dsfff',
  riskMessageAr: 'fffffff',
  generalInformationEn: 'fdsfasd',
  generalInformationAr: 'fasdfas',
  financialInformationEn: 'asdfasdfasdfa',
  financialInformationAr: 'dfasdf',
  updatesEn: 'asdfasdf',
  updatesAr: 'asdfasdfasdfa',
  imageDimension: '800x600',

  attachments: [
    {
      name: 'Document 1',
      type: 'pdf',
      size: 1024,
      key: 'doc1Key',
    },
    {
      name: 'Image 1',
      type: 'image',
      size: 2048,
      key: 'img1Key',
    },
  ],

  images: ['https://images.unsplash.com/photo-1621961458348-f013d219b50c'],
};
